[project]
name = "linkedin"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pillow>=11.1.0",
    "playwright>=1.49.1",
    "pyautogui>=0.9.54",
    "python-dotenv>=1.0.1",
]
